layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.6091301
  lightness: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0
name: kishikaisei
